server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8

# 日志配置
logging:
  level:
    cn.sc.anke.digital: debug
    org.springframework: warn

# open-ai 配置
open-ai:
  # 超时时间
  timeout_seconds: 60
  chat_GPT:
    # 使用什么采样温度。较高的值意味着模型将承担更多风险。为更有创意的应用程序尝试 0.8，为具有明确答案的应用程序尝试 0（argmax 采样）。
    temperature: 0.8
    # 要生成的最大字符数
    max_token: 2048
    # 一种替代温度采样的方法，称为核采样
    top_p: 1.0
